"""
Configurable skills dictionary and keyword aliases.

Expand SKILLS_BY_CATEGORY or SKILL_ALIASES to support more terms.
"""

SKILLS_BY_CATEGORY: dict[str, list[str]] = {
    "programming": [
        "Python",
        "Java",
        "JavaScript",
        "TypeScript",
        "C++",
        "C#",
        "Go",
        "Rust",
        "Ruby",
        "PHP",
        "Swift",
        "Kotlin",
        "R",
        "Scala",
        "HTML",
        "CSS",
    ],
    "frameworks": [
        "FastAPI",
        "Flask",
        "Django",
        "React",
        "Angular",
        "Vue",
        "Node.js",
        "Express",
        "Spring Boot",
        "Spring",
        ".NET",
        "Next.js",
    ],
    "databases": [
        "SQL",
        "MySQL",
        "PostgreSQL",
        "SQLite",
        "MongoDB",
        "Redis",
        "Oracle",
        "MariaDB",
        "DynamoDB",
    ],
    "cloud": [
        "AWS",
        "Azure",
        "GCP",
        "Google Cloud",
        "EC2",
        "S3",
        "Lambda",
        "Kubernetes",
    ],
    "tools": [
        "Git",
        "GitHub",
        "GitLab",
        "Docker",
        "Jenkins",
        "CI/CD",
        "Jira",
        "Linux",
        "Bash",
        "Postman",
    ],
    "data_ml": [
        "Pandas",
        "NumPy",
        "scikit-learn",
        "TensorFlow",
        "PyTorch",
        "Machine Learning",
        "Deep Learning",
        "NLP",
        "Data Analysis",
        "Data Science",
    ],
    "other": [
        "REST API",
        "REST APIs",
        "RESTful API",
        "Microservices",
        "Agile",
        "Scrum",
        "API Development",
        "Object-Oriented Programming",
        "OOP",
        "Unit Testing",
        "TDD",
    ],
}

# Maps variations to a single canonical skill name for matching.
SKILL_ALIASES: dict[str, str] = {
    "rest apis": "REST API",
    "rest api": "REST API",
    "restful api": "REST API",
    "restful apis": "REST API",
    "restful": "REST API",
    "java script": "JavaScript",
    "js": "JavaScript",
    "typescript": "TypeScript",
    "ts": "TypeScript",
    "node js": "Node.js",
    "node": "Node.js",
    "postgres": "PostgreSQL",
    "postgresql": "PostgreSQL",
    "mysql": "MySQL",
    "mongodb": "MongoDB",
    "mongo": "MongoDB",
    "machine learning": "Machine Learning",
    "ml": "Machine Learning",
    "deep learning": "Deep Learning",
    "scikit learn": "scikit-learn",
    "sklearn": "scikit-learn",
    "amazon web services": "AWS",
    "google cloud platform": "GCP",
    "google cloud": "GCP",
    "ci cd": "CI/CD",
    "cicd": "CI/CD",
    "api development": "API Development",
    "oop": "Object-Oriented Programming",
    "object oriented programming": "Object-Oriented Programming",
    "spring boot": "Spring Boot",
    "next js": "Next.js",
    "nextjs": "Next.js",
    "react js": "React",
    "reactjs": "React",
    "vue js": "Vue",
    "vuejs": "Vue",
    "angular js": "Angular",
    "fast api": "FastAPI",
    "github actions": "GitHub",
    "py": "Python",
    "k8s": "Kubernetes",
}
